version: '3.8'
services:
  janus:
    image: l3tnun/janus-gateway
    container_name: janus
    network_mode: "host"
    restart: always
    environment:
      - "JANUS_LOG_LEVEL"
    volumes:
      - E:\S.piano\env\janus:/opt/janus/etc/janus
    command: [ "janus","-F","/opt/janus/etc/janus" ]

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - E:\S.piano\env\nginx\web:/usr/share/nginx/html
      - E:\S.piano\env\nginx\nginx01:/etc/nginx/nginx.conf
    ports:
      - "80:80"